### ISSUE TITLE
Add configurable server address

### ISSUE THREAD

**Issue by anton-s-morozov** [OrcJMR/RubiusGoty#7]
Probably in lobby, but don't forget to abort game if no server.

**Comment by Shaddix** [comment]
Could be resolved by:
var webSocketUrl = "ws://" + location.host;

that way it'll always connect to the same server that is running http

**Comment by anton-s-morozov** [comment]
Updated message server for github to wss://cactus-trapezoid.glitch.me/
If not github, using wss://location.host

Added "join the game at ..." to Game and Lobby. `location.host` is displayed there, unless loading from github (shows "/RubiusGoty" address) or overridden in `socketsconfig.js`
